//
//  MovieDetailsInteractor.swift
//  MovieDB
//
//  Created by Yury Shubin on 23.01.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic {
	func exec(_ request: MovieDetails.Show.Request)
}

protocol MovieDetailsDataStore {
	var movie: BLMovie? { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore {
	var movie: BLMovie?
    var presenter: MovieDetailsPresentationLogic?
	
	func exec(_ request: MovieDetails.Show.Request) {
		let movie = MovieDetails.SharedViewModel.DisplayMovie(self.movie!)
		self.presenter?.presentMovie(response: MovieDetails.Show.Response(movie: movie))
	}
}
