//
//  MoviesRouter.swift
//  MovieDB
//
//  Created by Yury Shubin on 22.01.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MoviesRoutingLogic
{
	func routeToMovieDetailsVC(segue: UIStoryboardSegue?)
}

protocol MoviesDataPassing
{
    var dataStore: MoviesDataStore! { get }
}

class MoviesRouter: NSObject, MoviesRoutingLogic, MoviesDataPassing
{
    weak var vc: MoviesVC!
    var dataStore: MoviesDataStore!
    
    // MARK: Routing
	func routeToMovieDetailsVC(segue: UIStoryboardSegue?) {
		if let segue = segue {			
			let destinationVC = segue.destination as! MovieDetailsVC
			var destinationDS = destinationVC.router.dataStore!
			self.passDataToDetailsVC(source: self.dataStore, destination: &destinationDS)
		}
	}
	
	func passDataToDetailsVC(source: MoviesDataStore, destination: inout MovieDetailsDataStore) {
		destination.movie = source.selectedMovie
	}
}
